default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  username: <%= ENV.fetch("PG_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: base_rails_8_development

test:
  <<: *default
  database: base_rails_8_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  database: queue

cache:
  <<: *default
  database: cache

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
